# Generated by Django 6.0.4 on 2026-04-24 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('stream_url', models.URLField(blank=True, help_text='URL stream CCTV (RTSP/HTTP)')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL thumbnail/snapshot kamera')),
                ('is_active', models.BooleanField(default=True)),
                ('detection_result', models.CharField(choices=[('no_flood', 'Tidak Banjir'), ('flood', 'Banjir Terdeteksi'), ('uncertain', 'Tidak Pasti'), ('offline', 'Kamera Offline')], default='offline', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score YOLOv8 (0-1)')),
                ('last_detected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='areas.area')),
            ],
            options={
                'verbose_name': 'Kamera CCTV',
                'verbose_name_plural': 'Kamera CCTV',
                'db_table': 'cctv_cameras',
                'ordering': ['area__name', 'name'],
            },
        ),
    ]
