# Generated by Django 6.0.4 on 2026-04-27 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSimulasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Judul video simulasi', max_length=200)),
                ('video_file', models.FileField(help_text='Upload file video (.mp4)', upload_to='simulations/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='areas.area')),
            ],
            options={
                'verbose_name': 'Video Simulasi',
                'verbose_name_plural': 'Video Simulasi',
                'db_table': 'video_simulasi',
            },
        ),
    ]
