# Generated by Django 6.0.4 on 2026-04-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('cctv', '0002_videosimulasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('cctv', 'CCTV Live'), ('simulation', 'Video Simulasi')], default='cctv', max_length=20)),
                ('source_name', models.CharField(blank=True, help_text='Nama kamera / judul video', max_length=200)),
                ('status_banjir', models.CharField(choices=[('banjir', 'BANJIR'), ('banjir_ringan', 'BANJIR RINGAN'), ('hanya_genangan', 'HANYA GENANGAN'), ('aman', 'AMAN (TIDAK BANJIR)')], default='aman', max_length=30)),
                ('is_flood', models.BooleanField(default=False)),
                ('has_water', models.BooleanField(default=False)),
                ('water_area_ratio', models.FloatField(default=0.0, help_text='Persentase area genangan (0-100%)')),
                ('water_level_text', models.CharField(blank=True, max_length=100)),
                ('rain_intensity', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('recommendation', models.TextField(blank=True)),
                ('total_objects_detected', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score rata-rata (0-100)')),
                ('model_used', models.CharField(default='best.pt', max_length=100)),
                ('frame_size', models.CharField(blank=True, max_length=30)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_logs', to='areas.area')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_logs', to='cctv.cctvcamera')),
            ],
            options={
                'verbose_name': 'Log Analisis AI',
                'verbose_name_plural': 'Log Analisis AI',
                'db_table': 'flood_analysis_logs',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
