# Generated by Django 4.2.16 on 2026-05-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0003_floodanalysislog'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodanalysislog',
            name='evidence',
            field=models.TextField(blank=True, help_text='Ringkasan evidence permukaan tanah dari AI'),
        ),
        migrations.AddField(
            model_name='floodanalysislog',
            name='frame_results',
            field=models.JSONField(blank=True, default=list, help_text='Hasil analisis per-frame beserta evidence'),
        ),
        migrations.AlterField(
            model_name='cctvcamera',
            name='detection_result',
            field=models.CharField(choices=[('no_flood', 'Tidak Banjir'), ('mulai_banjir', 'Sudah Mulai Banjir'), ('flood', 'Sudah Banjir'), ('uncertain', 'Tidak Pasti'), ('offline', 'Kamera Offline')], default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='floodanalysislog',
            name='status_banjir',
            field=models.CharField(choices=[('banjir', 'Sudah Banjir'), ('siaga', 'Siaga'), ('banjir_ringan', 'Sudah Mulai Banjir'), ('hanya_genangan', 'HANYA GENANGAN'), ('aman', 'AMAN (TIDAK BANJIR)')], default='aman', max_length=30),
        ),
    ]
