# Generated by Django 6.0.4 on 2026-04-24 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama lokasi (contoh: Kampung Melayu)', max_length=200)),
                ('district', models.CharField(help_text='Kota/Kabupaten (contoh: Jakarta Timur)', max_length=100)),
                ('sub_district', models.CharField(blank=True, help_text='Kecamatan', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('status', models.CharField(choices=[('aman', 'Aman'), ('potensial', 'Potensial'), ('banjir', 'Banjir')], default='aman', max_length=20)),
                ('water_level_cm', models.FloatField(default=0.0, help_text='Ketinggian air dalam cm')),
                ('water_level_change', models.FloatField(default=0.0, help_text='Perubahan ketinggian air cm/jam')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wilayah',
                'verbose_name_plural': 'Wilayah',
                'db_table': 'areas',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='areas.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Area Tersimpan',
                'verbose_name_plural': 'Area Tersimpan',
                'db_table': 'saved_areas',
                'unique_together': {('user', 'area')},
            },
        ),
    ]
