# Generated by Django 4.2.16 on 2026-05-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='ai_confidence_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='area',
            name='area_tergenang',
            field=models.FloatField(default=0.0, help_text='Estimasi persentase area tergenang dari AI (0-100)'),
        ),
        migrations.AddField(
            model_name='area',
            name='last_ai_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='status_genangan',
            field=models.CharField(default='Tidak Ada Genangan', max_length=80),
        ),
        migrations.AlterField(
            model_name='area',
            name='status',
            field=models.CharField(choices=[('aman', 'Aman'), ('siaga', 'Siaga'), ('potensial', 'Sudah Mulai Banjir'), ('banjir', 'Sudah Banjir')], default='aman', max_length=20),
        ),
    ]
