# Generated by Django 6.0.4 on 2026-04-24 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='openweather', max_length=20)),
                ('forecast_time', models.DateTimeField(help_text='Waktu yang diprakirakan')),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('rainfall', models.FloatField(blank=True, help_text='Prediksi curah hujan mm/jam (ARIMA)', null=True)),
                ('rainfall_probability', models.IntegerField(default=0, help_text='Probabilitas hujan 0-100%')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='areas.area')),
            ],
            options={
                'verbose_name': 'Prakiraan Cuaca',
                'verbose_name_plural': 'Prakiraan Cuaca',
                'db_table': 'weather_forecasts',
                'ordering': ['forecast_time'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('bmkg', 'BMKG'), ('openweather', 'OpenWeatherMap'), ('weatherapi', 'WeatherAPI.com')], default='bmkg', max_length=20)),
                ('temperature', models.FloatField(blank=True, help_text='Suhu dalam Celsius', null=True)),
                ('humidity', models.IntegerField(blank=True, help_text='Kelembaban dalam %', null=True)),
                ('rainfall', models.FloatField(default=0.0, help_text='Curah hujan dalam mm/jam')),
                ('wind_speed', models.FloatField(blank=True, help_text='Kecepatan angin km/jam', null=True)),
                ('description', models.CharField(blank=True, help_text='Deskripsi cuaca', max_length=255)),
                ('weather_code', models.CharField(blank=True, help_text='Kode cuaca dari sumber', max_length=50)),
                ('raw_data', models.JSONField(default=dict, help_text='Data mentah dari API')),
                ('recorded_at', models.DateTimeField(help_text='Waktu data diambil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, help_text='Wilayah terkait (null = data umum Jakarta)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='areas.area')),
            ],
            options={
                'verbose_name': 'Data Cuaca',
                'verbose_name_plural': 'Data Cuaca',
                'db_table': 'weather_data',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['area', '-recorded_at'], name='weather_dat_area_id_c5abc7_idx'), models.Index(fields=['-recorded_at'], name='weather_dat_recorde_fdfc18_idx')],
            },
        ),
    ]
